Add -lpthread to LDFLAGS for building tests
This change fixes the following linker error when compiling cata_test
on Linux, using either gcc or clang:

/usr/bin/ld: obj/tiles/test_main.o:
    undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0:
    error adding symbols: DSO missing from command line