Silence clang-tidy complaints about use of __func__ in debugmsg
Use of debugmsg() inside lambdas results in clang complaining
that __func__ does not capture the function name correctly.
Which is fair, but we can't do anything about that, and explicitly
passing in the function name every time is more trouble than it's worth.

Example output:

.\src\achievement.cpp:364:9: error: inside a lambda, '__func__' expands to the name of the function call operator; consider capturing the name of the enclosing function explicitly [bugprone-lambda-function-name,-warnings-as-errors]
  364 |         cata_fatal( "Invalid epoch" );
      |         ^
.\src/debug.h:85:9: note: expanded from macro 'cata_fatal'
   85 |         debugmsg(__VA_ARGS__); \
      |         ^
.\src/debug.h:69:64: note: expanded from macro 'debugmsg'
   69 | #define debugmsg(...) realDebugmsg(__FILE__, STRING(__LINE__), CATA_FUNCTION_NAME, __VA_ARGS__)
      |                                                                ^
.\src/debug.h:60:28: note: expanded from macro 'CATA_FUNCTION_NAME'
   60 | #define CATA_FUNCTION_NAME __func__