stl_emulation span::count_ is not const anymore
In C++ we cannot have both assignment operator and const member. Since
span::operator= is defined, span::count_ constness must be removed.

cherry-picked from upstream
google/flatbuffers@20aad0c41e1252b04c72111c3eb221280a9c2009.

fixes:

	In file included from ../src/third-party/flatbuffers/util.h:25,
			 from ../src/third-party/flatbuffers/flexbuffers.h:26,
			 from ../src/flexbuffer_json.h:9,
			 from ../src/json.h:1623,
			 from ../src/units.h:17,
			 from ../src/damage.h:18,
			 from ../src/bodypart.h:15,
			 from ../src/avatar.h:16,
			 from ../tests/battery_mod_test.cpp:9:
	../src/third-party/flatbuffers/stl_emulation.h: In member function ‘constexpr flatbuffers::span<T, Extent>& flatbuffers::span<T, Extent>::operator=(const flatbuffers::span<T, Extent>&)’:
	../src/third-party/flatbuffers/stl_emulation.h:550:12: error: assignment of read-only member ‘flatbuffers::span<T, Extent>::count_’
	  550 |     count_ = other.count_;
	      |     ~~~~~~~^~~~~~~~~~~~~~

under gcc 14.