Fix GCC build error
src/mapgen.cpp: In member function 'void map::draw_map(oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, int, float, int, const regional_settings*)':
src/mapgen.cpp:5419:56: error：assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
                         for (int j = p.y; j <= p.y + 5 && okay; j++) {
                                           ~~~~~~~~~~~~~^~~~~~~
src/mapgen.cpp:5482:56: error：assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
                         for (int j = p.y; j <= p.y + 5 && okay; j++) {
                                           ~~~~~~~~~~~~~^~~~~~~