Explicitly remove precompiled headers by extension (#43080)
The regex form `{gch,pch,d}` does not work to remove these files on my
Ubuntu linux system. Expanding this into three `rm` statements correctly
removes the files when doing a `make clean`, preventing this error

fatal error: file '.../tests/../src/../pch/main-pch.hpp' has been
modified since the precompiled header 'pch/tests-pch.hpp.pch' was built:
size changed