bug(overmap): fix FTBFS on OS X 10.6
 * Compilation fails on OS X 10.6 with the following error message:

    g++ -DMACOSX -Werror -Wall -Wextra -Wno-switch -Wno-sign-compare -Wno-missing-braces -Wno-unused-parameter -g   -MMD -mmacosx-version-min=10.6 -c src/addiction.cpp -o obj/addiction.o
    In file included from src/map.h:14,
                     from src/game.h:6,
                     from src/addiction.cpp:2:
    /usr/include/c++/4.2.1/bits/stl_map.h: In instantiation of ‘std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, oter_t&, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, oter_t&> > >’:
    src/overmap.h:47:   instantiated from here
    /usr/include/c++/4.2.1/bits/stl_map.h:342: error: forming reference to reference type ‘oter_t&’
    /usr/include/c++/4.2.1/bits/stl_map.h:364: error: forming reference to reference type ‘oter_t&’
    /usr/include/c++/4.2.1/bits/stl_map.h:373: error: forming reference to reference type ‘oter_t&’
    /usr/include/c++/4.2.1/bits/stl_pair.h: In instantiation of ‘std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, oter_t&>’:
    src/overmap.h:52:   instantiated from here
    /usr/include/c++/4.2.1/bits/stl_pair.h:84: error: forming reference to reference type ‘oter_t&’
    make: *** [obj/addiction.o] Error 1

   Fixed by removing & from oter&.