advanced_inv: fix false-positive -Wmaybe-uninitialized
I've only seen this error crop up on LTO:

    src/advanced_inv.cpp: In function ‘advanced_inv’:
    src/advanced_inv.cpp:1450:21: error: ‘changeSquare’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
			 if(changeSquare == AIM_DRAGGED) {
			 ^
    lto1: all warnings being treated as errors

It looks totally bogus to me. changeSquare would only be uninitialized if
::get_square() returned false. But it couldn't have, if we reached line
1450.

Simplest solution is to initialize changeSquare to a bogus value and shut GCC
up.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>